name: CI for Puppetfile Resolver

on:
  push:
    branches:
      - master

jobs:
  build:
    name: CI Tasks
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7]
        check: [rspec]
        os: [ubuntu-latest, windows-latest]
        include:
          # Run linting
          - ruby: 2.7
            os: ubuntu-latest
            check: rubocop
          # Test on the oldest ruby we support
          - ruby: 2.5
            os: ubuntu-latest
            check: rspec
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Output Ruby Information
        run: |
          echo "Ruby version"
          ruby --version
          echo "gem version"
          gem --version
          echo "bundler version"
          bundle -v
      - run: bundle exec ${{ matrix.check }}
